### ISSUE TITLE
"tcpeek -h" show invalid expression sample.

### ISSUE THREAD

**Issue by zu2** [pandax381/tcpeek#4]
tcpeek -h で表示されるサンプルにて RX/TX ではなく IN/OUT が使われています。

src/init.c
	printf("    tcpeek -i eth0 filter:IN@%%:80:443\n");
	printf("    tcpeek -i eth0 filter:OUT@192.168.0.0/24:%%\n");
	printf("    tcpeek -i eth0 inbound-filter:IN@%%:%% outbound-filter:OUT@192.168.0.100:%%,192.168.0.200:%%\n");

inbound-filter/outbound-filter という記述も src/init.c にしか存在しないので多分間違いだと思う。

**Comment by pandax381** [comment]
ありがとうございます。

ご指摘の通り、help に出力しているメッセージが間違っていますね。
もともとは IN/OUT としていたものを RX/TX に変更した時点でメッセージの修正だけが漏れてしまっていたようです...こらはすぐに修正します。

もう一点の inbound-filter/outbound-filter の記述についてですが、こちらは任意に指定できる「フィルタ名」ですので、ソースコード中には登場する文字列ではありません。

**Comment by zu2** [comment]
了解いたしました。
